import Head from 'next/head';
import { useEffect, useState } from 'react';
import supabase from './supabaseClient';
import SmoothieCard from './components/SmoothieCard';
import Link from 'next/link';

export default function Home() {
  const [fetchError, setFetchError] = useState(null);
  const [smoothies, setSmoothies] = useState(null);

  useEffect(() => {
    const fetchSmoothies = async () => {
      const { data, error } = await supabase.from('smoothies').select();

      if (error) {
        setFetchError('could not fetch the smoothies.');
        setSmoothies(null);
        console.log(error);
      }

      if (data) {
        setFetchError(null);
        setSmoothies(data);
      }
    };
    fetchSmoothies();
  }, []);
  return (
    <div className="">
      <Head>
        <title>Best Smoothie Shop in Pyin Oo Lwin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        ></link> */}
      </Head>
      <nav>
        <div>
          <h3> Smoothie Logo</h3>
        </div>
        <Link href="/components/Create">
          <a>Create Smoothies</a>
        </Link>
      </nav>
      <main>
        {fetchError && <p>{fetchError}</p>}
        {smoothies && (
          <div className="smoothie-grid">
            {smoothies.map((smoothie) => (
              // eslint-disable-next-line react/no-unknown-property
              <SmoothieCard key={smoothie.id} smoothie={smoothie} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
